version: "3.8"

services:

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672

  transport-commands:
    build:
      context: ../transport_service_commands/
      dockerfile: Dockerfile
    container_name: 'transport-commands'
    restart: always
    depends_on:
      - rabbitmq
      - postgres-db
    environment:
      - POSTGRES_USR=admin
      - POSTGRES_PWD=admin
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DATABASE=rsww
      - POSTGRES_PORT=5432
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  postgres-db:
    container_name: 'postgres-db'
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rsww
    ports:
      - 5432:5432

  transport-queries:
    build:
      context: ../transport_service_queries/
      dockerfile: Dockerfile
    container_name: 'transport-queries'
    restart: always
    depends_on:
      - rabbitmq
      - mongo-db
    environment:
      - MONGO_USER=admin
      - MONGO_PWD=admin
      - MONGO_HOST=mongo-db
      - MONGO_DATABASE=rsww
      - MONGO_PORT=27017
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  mongo-db:
    container_name: 'mongo-db'
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: rsww
    ports:
      - 27017:27017

  api-gateway:
    build:
      context: ../api_gateway/
      dockerfile: Dockerfile
    container_name: 'api-gateway'
    restart: always
    ports:
      - 17515:8080
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  userservice:
    container_name: 'userservice'
    build:
      context: ../userservice/
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=rsww
      - AMQP_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - postgres-db

  frontend:
    container_name: 'frontend'
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:80

  payment:
    build:
      context: ../payment_service
      dockerfile: Dockerfile
    container_name: 'payment'
    environment:
      - AMQP_URL=rabbitmq
      - REJECTION_PROBABILITY=10
    depends_on:
      - rabbitmq

  accommodation_service_commands:
    container_name: accommodation_service_commands
    build:
      context: ../accommodation_service_commands
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres-db
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=accommodation_service
      - POSTGRES_USER=admin
      - POSTGRES_PWD=admin
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  accommodation_service_queries:
    build:
      context: ../accommodation_service_queries
      dockerfile: Dockerfile
    container_name: accommodation_service_queries
    depends_on:
      - rabbitmq
      - mongo-db
    environment:
      - MONGO_USER=admin
      - MONGO_USER_PWD=admin
      - MONGO_HOST=mongo-db
      - DATABASE_NAME=trips
      - MONGO_PORT=27017
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  trip_service:
    container_name: trip_service
    build:
      context: ../trip_service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo-db
    environment:
      - MONGO_USER=admin
      - MONGO_USER_PWD=admin
      - MONGO_HOST=mongo-db
      - DATABASE_NAME=trips
      - MONGO_PORT=27017
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USR=guest
      - RABBIT_PWD=guest

  tour_operator:
    container_name: tour_operator
    build:
      context: ../tour_operator
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - AMQP_URL=rabbitmq
      - REJECTION_PROBABILITY=10
      